services:
  bot:
    build: .
    image: ${IMAGE_REPO_PATH:-ghcr.io/svoi-bot/svoi-bot}@${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      SQLITE_PATH: /data/svoi.db
      BOT_TOKEN: ${BOT_TOKEN}
    env_file:
      - .envrc
    command: "-config /config.yaml"
    volumes:
      - ./data:/data
      - ./config/config.yaml:/config.yaml:ro
