services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - SQLITE_PATH=/data/svoi.db
    env_file:
      - .envrc
    command: "-config /config.yaml"
    volumes:
      - ./data:/data
      - ./config/config.yaml:/config.yaml:ro
