metrics:
  addr: ":9080"
  update_period: 15s

sticker_sets:
  - name: "SVOMonions"
    exclude_sticker_ids:
      - "AAMCAgADGQEAAS9VuWc0jrYE1AAB_glDF-WLgGpCaCgCiQACSk4AAtZGQEpZ2czOT2dA6AEAB20AAzYE"
  - name: "GOYDAAAAAAAAAAAAAAAAAAAA"
    exclude_sticker_ids:
      - "AAMCAgADGQEAAS9VxWc0jvTwlMB5es__NRxgLoR4ScRhAAI7SgACTPqgSZS4EcbGdcqUAQAHbQADNgQ"
      - "AAMCAgADGQEAAS_N92dTNle7HLC5fjfsbE4EY0Nl4Ed5AAIfRQACvxahSVYGPGFUUD6gAQAHbQADNgQ"

admin_ids:
  - 816878939

ai:
  base_url: https://openai.com/api/v1/chat/completions
  model: "gpt-4o-mini"
  reset_period: 1h
  system_prompt: |
    ...
