// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package q

type Stat struct {
	UserID            int64
	ChatID            int64
	SvoCount          int64
	ZovCount          int64
	LikvidirovanCount int64
}

type User struct {
	ID            int64
	DisplayedName string
}
