name: Build docker image and publish it to github container registry

on:
  workflow_dispatch: {}

jobs:
  publish_package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/leksus-04/svoi-bot:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote server and update running container
        uses: appleboy/ssh-action@v1.1.0
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_ADDRESS }}
          username: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          port: ${{ secrets.DEPLOYMENT_SERVER_SSH_PORT }}
          envs: BOT_TOKEN
          script: |
            cd ${{ secrets.DEPLOYMENT_SERVER_PATH }}
            git pull
            docker compose pull
            docker compose down -t 10 || true
            docker compose up -d
