name: Build & Deploy

on:
  workflow_dispatch: {}

env:
  IMAGE_REPO_PATH: ghcr.io/leksus-04/svoi-bot

jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    outputs:
      image_id: ${{ steps.push.outputs.imageid }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_REPO_PATH }}:latest

  deploy:
    name: Deploy
    needs: publish_package
    runs-on: ubuntu-latest
    steps:
      - name: SSH into remote server and update running container
        uses: appleboy/ssh-action@v1.1.0
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
          IMAGE: ${{ env.IMAGE_REPO_PATH }}@${{ needs.publish_package.outputs.image_id }}
          CONFIG: ${{ secrets.CONFIG }}
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_ADDRESS }}
          username: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          port: ${{ secrets.DEPLOYMENT_SERVER_SSH_PORT }}
          envs: BOT_TOKEN,IMAGE,AI_API_KEY,CONFIG
          script: |
            cd ${{ secrets.DEPLOYMENT_SERVER_PATH }}
            git pull
            echo "$CONFIG" > ~/config/config.yaml
            docker compose pull
            docker compose down -t 10 || true
            docker compose up -d
